### ISSUE TITLE
How to update a record for CoreData

### ISSUE THREAD

**Issue by ieiayaobb** [iascchen/SwiftCoreDataSimpleDemo#3]
Actually, I didn't find any demo code for updating. Can you tell me how to do this?

**Comment by iascchen** [comment]
Fetched the recoreds, modify its attribute, and savecontext.

var result = self.cdh.managedObjectContext!.executeFetchRequest(fReq, error:&error)
for resultItem in result! {
var memberItem = resultItem as Member
memberItem.name = newItemName
}

self.cdh.saveContext(self.cdh.managedObjectContext!)

**Comment by ieiayaobb** [comment]
Thanks a lot
