### ISSUE TITLE
Google Analytics & UIViewController

### ISSUE THREAD

**Issue by Jamal1337** [iascchen/SwiftCoreDataSimpleDemo#4]
Hi, I'm trying to implement your CoreDataHelper/Store and within the AppDelegate everything works fine, but I have Google Analytics in my project which accesses CoreData directly at the app launch and then the UI freezes and I cannot do anything.
I tried disabling GA and the UI responds, but when trying to save something to CoreData within a UIViewController I get the save log message but nothing was stored.

Do you have any advice and/or sample code? Thanks!

**Comment by iascchen** [comment]
Please make sure you used same contenxt with GA. In my code, i used 2 context to handle background store:

self.cdh.saveContext(self.cdh.backgroundContext!)
self.cdh.saveContext(self.cdh.managedObjectContext!)

**Comment by Jamal1337** [comment]
Thanks, I managed to get it work by changing the observer to:

NSNotificationCenter.defaultCenter().addObserver(self, selector: "contextDidSaveContext:", name: NSManagedObjectContextDidSaveNotification, object: self.managedObjectContext)
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "contextDidSaveContext:", name: NSManagedObjectContextDidSaveNotification, object: self.backgroundContext)
